"""new table for bought entries with unknown items

Revision ID: 24b8e319c0d0
Revises: 015f4256bb4c
Create Date: 2024-06-02 13:14:38.681605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24b8e319c0d0'
down_revision = '015f4256bb4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.alter_column('token',
               existing_type=sa.VARCHAR(length=15),
               nullable=True)
        batch_op.drop_constraint('payment_token_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'login_token', ['token'], ['token'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('payment_token_fkey', 'login_token', ['token'], ['token'], onupdate='CASCADE', ondelete='CASCADE')
        batch_op.alter_column('token',
               existing_type=sa.VARCHAR(length=15),
               nullable=False)

    # ### end Alembic commands ###
