"""raise bonid digits

Revision ID: 926395732c3e
Revises: 2a64d3b9235a
Create Date: 2024-08-24 10:33:39.109944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '926395732c3e'
down_revision = '2a64d3b9235a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('receipt', schema=None) as batch_op:
        batch_op.alter_column('bonid',
               existing_type=sa.NUMERIC(precision=24, scale=0),
               type_=sa.Numeric(precision=28, scale=0),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('receipt', schema=None) as batch_op:
        batch_op.alter_column('bonid',
               existing_type=sa.Numeric(precision=28, scale=0),
               type_=sa.NUMERIC(precision=24, scale=0),
               existing_nullable=True)

    # ### end Alembic commands ###
