name: Create Release
on: 
  push:
    tags:
    - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Archive Server
      uses: thedoctor0/zip-release@master
      with:
        type: 'zip'
        filename: 'server.zip'
        exclusions: '*.git*'
    - name: Release Archive
      uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        artifacts: "server.zip"
        token: ${{ secrets.GITHUB_TOKEN }}
